[package]
name = "witness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
ruint = "1.10.0"
byteorder = "1.4.3"

[build-dependencies]
cxx-build = "1.0"
