[package]
name = "witness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
ruint = { version = "1.10.0", features = ["rand", "serde"] }
byteorder = "1.4.3"
hex = "0.4.3"
serde_json = "1.0.64"
rand = "0.8.5"
serde = { version = "1.0.190", features = ["derive"] }
postcard = { version = "1.0.8", features = ["use-std"], default-features = false }

[build-dependencies]
cxx-build = "1.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = true
